---
title: "Save data"
author: "Stefano Coretta"
date: "21/05/2019"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
library(usethis)
```

# Read data

```{r read-egg}
stimuli <- read_csv("data-raw/datasets/stimuli.csv")

ita_egg_raw <- read_csv("data-raw/datasets/measurements.csv", na = "--undefined--") %>%
  full_join(y = stimuli) %>%
  mutate(
    v1_duration = (c2_ons - v1_ons) * 1000,
    c2_clos_duration = (c2_rel - c2_ons) * 1000,
    rel_voff = (c2_ons - c1_rel) * 1000,
    sent_duration = sentence_off - sentence_ons,
    speech_rate = 8 / sent_duration,
    speech_rate_c = speech_rate - mean(speech_rate, na.rm = TRUE),
    voice_duration = (voice_off - voice_ons) * 1000,
    vot = (voice_ons - c1_rel) * 1000,
    voi_clo = (voice_off - c2_ons) * 1000,
    rel_rel = (c2_rel - c1_rel) * 1000,
    vowel = factor(vowel, levels = c("i", "e", "a", "o", "u")),
    height = factor(height, levels = c("low", "mid-low", "mid-high", "high")),
    c1_place = factor(c1_place, levels = c("labial", "coronal", "velar")),
    c2_place = factor(c2_place, levels = c("labial", "coronal", "velar"))
  )
```

```{r read-formants}
formants_files <- list.files("data-raw/data/raw/formants/", "aggregated_data.csv", recursive = TRUE, full.names = TRUE)

formants <- map_df(formants_files, read_csv) %>%
  mutate(
    speaker = str_sub(file, 1, 4)
  )

info_files <- list.files("data-raw/data/raw/formants/", "segmentation_info.csv", recursive = TRUE, full.names = TRUE)

formants_info <- map_df(info_files, read_csv) %>%
  rename("speaker" = inputfile, "file" = "outputfile")

formants <- left_join(formants, formants_info, by = c("file", "speaker")) %>%
  rename("duration" = duration.y)

formants_ids <- read_csv("data-raw/datasets/formants-ids.csv")

formants <- left_join(formants, formants_ids)
```

```{r}
ita_egg <- left_join(ita_egg_raw, formants) %>%
  select(speaker:f0, cutoff:f35)
```


# Use data

```{r use-data}
use_data(ita_egg, overwrite = TRUE)
use_data(formants, overwrite = TRUE)
```

